## cartridge.properties for cartridge int_jpmc_core
#Tue Jan 27 16:51:30 CEST 2026
demandware.cartridges.int_jpmc_core.multipleLanguageStorefront=true
demandware.cartridges.int_jpmc_core.id=int_jpmc_core