## cartridge.properties for cartridge int_jpmc_sfra
#Tue Jan 27 16:52:31 CEST 2026
demandware.cartridges.int_jpmc_sfra.multipleLanguageStorefront=true
demandware.cartridges.int_jpmc_sfra.id=int_jpmc_sfra