error.payment.processor.not.supported=The selected payment processor is not supported.
error.payment.not.valid=The selected payment method is not valid for this order.
error.payment.encryption.missing=Something went wrong. Please try again later.
error.payment.encryption.invalid=Something went wrong. Please try again later.
error.payment.verification.failed=Something went wrong. Please try again later.
error.payment.verification.exception=Something went wrong. Please try again later.
error.technical=Something went wrong. Please try again later.
error.payment.authorization.failed=Something went wrong. Please try again later.
error.fraud.declined=Your payment could not be processed due to security reasons. Please contact customer service.
error.payment.order.not.found=Order not found.

# Google Pay
label.googlepay=Google Pay

